import './languages/flink/flink.contribution';
import './languages/spark/spark.contribution';
import './languages/hive/hive.contribution';
import './languages/trino/trino.contribution';
import './sql/sql.contribution';
import './languages/mysql/mysql.contribution';
import './plsql/plsql.contribution';
import './languages/pgsql/pgsql.contribution';
import './languages/impala/impala.contribution';
