name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: npm install
        run: npm install

      - name: Test
        run: npm test
